name: Economy
main: com.goldhill.economy.Economy
author: Spenk
version: 0.0.1
commands:
    money:
        description: sends a message to the socket server
        usage: /sendsocket <args> - to send a message to the socket server!
    bank:
        description: sends a message to the socket server
        usage: /sendsocket <args> - to send a message to the socket server!